version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: emojify_backend
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "5100:5100"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py

volumes:
  backend_venv:

